from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_authWindow(object):
    def setupUi(self, authWindow):
        authWindow.setObjectName("authWindow")
        authWindow.setFixedSize(400, 300)
        authWindow.setWindowIcon(QIcon('chat.ico'))
        self.centralwidget = QtWidgets.QWidget(authWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.auth_label = QtWidgets.QLabel(self.centralwidget)
        self.auth_label.setGeometry(QtCore.QRect(136, 20, 161, 35))
        self.auth_label.setFont(QtGui.QFont("Segoe UI Variable",14))
        self.auth_label.setObjectName("auth_label")
        self.login_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_lineEdit.setGeometry(QtCore.QRect(110, 90, 181, 35))
        self.login_lineEdit.setFont(QtGui.QFont("Segoe UI Variable"))
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_lineEdit.setGeometry(QtCore.QRect(110, 140, 181, 35))
        self.password_lineEdit.setFont(QtGui.QFont("Segoe UI Variable"))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(50, 100, 55, 20))
        self.login_label.setFont(QtGui.QFont("Segoe UI Variable"))
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(40, 150, 55, 20))
        self.password_label.setFont(QtGui.QFont("Segoe UI Variable"))
        self.password_label.setObjectName("password_label")
        self.singIn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.singIn_btn.setGeometry(QtCore.QRect(30, 200, 161, 50))
        self.singIn_btn.setFont(QtGui.QFont("Segoe UI Variable"))
        self.singIn_btn.setObjectName("singIn_btn")
        self.signUp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signUp_btn.setGeometry(QtCore.QRect(210, 200, 161, 50))
        self.signUp_btn.setFont(QtGui.QFont("Segoe UI Variable"))
        self.signUp_btn.setObjectName("signUp_btn")
        self.message_box_label = QtWidgets.QLabel(self.centralwidget)
        self.message_box_label.setGeometry(QtCore.QRect(10, 60, 381, 20))
        self.message_box_label.setFont(QtGui.QFont("Segoe UI Variable"))
        self.message_box_label.setAutoFillBackground(False)
        self.message_box_label.setLineWidth(-1)
        self.message_box_label.setMidLineWidth(0)
        self.message_box_label.setText("")
        self.message_box_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_box_label.setObjectName("message_box_label")
        authWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(authWindow)
        QtCore.QMetaObject.connectSlotsByName(authWindow)

    def retranslateUi(self, authWindow):
        _translate = QtCore.QCoreApplication.translate
        authWindow.setWindowTitle(_translate("authWindow", "authWindow"))
        self.auth_label.setText(_translate("authWindow", "Authentification"))
        self.login_label.setText(_translate("authWindow", "login"))
        self.password_label.setText(_translate("authWindow", "password"))
        self.singIn_btn.setText(_translate("authWindow", "Sign In"))
        self.signUp_btn.setText(_translate("authWindow", "Sign Up"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authWindow = QtWidgets.QMainWindow()
    ui = Ui_authWindow()
    ui.setupUi(authWindow)
    authWindow.show()
    sys.exit(app.exec_())
