from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_authWindow(object):
    def setupUi(self, authWindow):
        authWindow.setObjectName("authWindow")
        authWindow.setFixedSize(400, 300)
        authWindow.setWindowIcon(QIcon('chat.ico'))
        self.centralwidget = QtWidgets.QWidget(authWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 161, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 90, 181, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 140, 181, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 55, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 55, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Button_login = QtWidgets.QPushButton(self.centralwidget)
        self.Button_login.setGeometry(QtCore.QRect(30, 200, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.Button_login.setFont(font)
        self.Button_login.setObjectName("Button_login")
        self.Button_registr = QtWidgets.QPushButton(self.centralwidget)
        self.Button_registr.setGeometry(QtCore.QRect(210, 200, 161, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.Button_registr.setFont(font)
        self.Button_registr.setObjectName("Button_registr")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setLineWidth(-1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        authWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(authWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        authWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(authWindow)
        self.statusbar.setObjectName("statusbar")
        authWindow.setStatusBar(self.statusbar)

        self.retranslateUi(authWindow)
        QtCore.QMetaObject.connectSlotsByName(authWindow)

    def retranslateUi(self, authWindow):
        _translate = QtCore.QCoreApplication.translate
        authWindow.setWindowTitle(_translate("authWindow", "authWindow"))
        self.label.setText(_translate("authWindow", "Authentification"))
        self.label_2.setText(_translate("authWindow", "login"))
        self.label_3.setText(_translate("authWindow", "password"))
        self.Button_login.setText(_translate("authWindow", "SignIn"))
        self.Button_registr.setText(_translate("authWindow", "SignUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authWindow = QtWidgets.QMainWindow()
    ui = Ui_authWindow()
    ui.setupUi(authWindow)
    authWindow.show()
    sys.exit(app.exec_())
