from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_chatWindow(object):
    def setupUi(self, chatWindow):
        chatWindow.setObjectName("chatWindow")
        chatWindow.resize(500, 700)
        chatWindow.setWindowIcon(QIcon('chat.ico'))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.centralwidget = QtWidgets.QWidget(chatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.my_image_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gridLayout_2.addWidget(self.my_image_btn, 0, 0, 1, 1)
        self.my_login_label = QtWidgets.QLabel(self.centralwidget)
        self.my_login_label.setObjectName("my_login_label")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.my_login_label.setFont(font)
        self.gridLayout_2.addWidget(self.my_login_label, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.listWidget.setFont(font)
        self.gridLayout_5.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.comboBox.setFont(font)
        self.gridLayout_3.addWidget(self.comboBox, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.gridLayout_4.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.ListWidget = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.gridLayout_4.addWidget(self.ListWidget, 0, 0, 1, 1)
        self.send_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_msg_btn.setObjectName("send_msg_btn")
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.send_msg_btn.setFont(font)
        self.gridLayout_4.addWidget(self.send_msg_btn, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 0, 1, 1)

        chatWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(chatWindow)
        QtCore.QMetaObject.connectSlotsByName(chatWindow)

    def retranslateUi(self, chatWindow):
        _translate = QtCore.QCoreApplication.translate
        chatWindow.setWindowTitle(_translate("chatWindow", "chatWindow"))
        self.my_login_label.setText(_translate("chatWindow", "TextLabel"))

        self.send_msg_btn.setText(_translate("chatWindow", "Send message"))