from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_chatWindow(object):
    def setupUi(self, chatWindow):
        chatWindow.setObjectName("chatWindow")
        chatWindow.resize(400, 600)
        chatWindow.setMinimumSize(QtCore.QSize(400, 600))
        chatWindow.setWindowIcon(QIcon('chat.ico'))
        self.centralwidget = QtWidgets.QWidget(chatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.my_login = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.my_login.sizePolicy().hasHeightForWidth())
        self.my_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.my_login.setFont(font)
        self.my_login.setText("")
        self.my_login.setObjectName("my_login")
        self.gridLayout.addWidget(self.my_login, 1, 1, 1, 1)
        self.friends_list = QtWidgets.QListWidget(self.centralwidget)
        self.friends_list.setObjectName("friends_list")
        self.gridLayout.addWidget(self.friends_list, 4, 0, 1, 2)
        self.friend_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.friend_image.sizePolicy().hasHeightForWidth())
        self.friend_image.setSizePolicy(sizePolicy)
        self.friend_image.setMinimumSize(QtCore.QSize(100, 100))
        self.friend_image.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.friend_image.setFont(font)
        self.friend_image.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.friend_image.setText("")
        self.friend_image.setObjectName("friend_image")
        self.gridLayout.addWidget(self.friend_image, 1, 3, 3, 1)
        self.msg_list = QtWidgets.QListWidget(self.centralwidget)
        self.msg_list.setObjectName("msg_list")
        self.gridLayout.addWidget(self.msg_list, 4, 2, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 5, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 2, 1, 2)
        self.send_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_msg_btn.sizePolicy().hasHeightForWidth())
        self.send_msg_btn.setSizePolicy(sizePolicy)
        self.send_msg_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.send_msg_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.send_msg_btn.setFont(font)
        self.send_msg_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.gridLayout.addWidget(self.send_msg_btn, 6, 2, 1, 2)
        self.find_friends_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_friends_btn.sizePolicy().hasHeightForWidth())
        self.find_friends_btn.setSizePolicy(sizePolicy)
        self.find_friends_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.find_friends_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.find_friends_btn.setFont(font)
        self.find_friends_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.find_friends_btn.setObjectName("find_friends_btn")
        self.gridLayout.addWidget(self.find_friends_btn, 6, 0, 1, 2)
        self.friend_login = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.friend_login.sizePolicy().hasHeightForWidth())
        self.friend_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.friend_login.setFont(font)
        self.friend_login.setText("")
        self.friend_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.friend_login.setObjectName("friend_login")
        self.gridLayout.addWidget(self.friend_login, 1, 2, 1, 1)
        self.my_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.my_image.sizePolicy().hasHeightForWidth())
        self.my_image.setSizePolicy(sizePolicy)
        self.my_image.setMinimumSize(QtCore.QSize(100, 100))
        self.my_image.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.my_image.setFont(font)
        self.my_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.my_image.setObjectName("my_image")
        self.gridLayout.addWidget(self.my_image, 1, 0, 3, 1)
        self.my_activity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.my_activity.setFont(font)
        self.my_activity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.my_activity.setObjectName("my_activity")
        self.gridLayout.addWidget(self.my_activity, 2, 1, 1, 1)
        self.friend_activity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        self.friend_activity.setFont(font)
        self.friend_activity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.friend_activity.setObjectName("friend_activity")
        self.gridLayout.addWidget(self.friend_activity, 2, 2, 1, 1)
        self.comboBox.raise_()
        self.lineEdit.raise_()
        self.send_msg_btn.raise_()
        self.my_image.raise_()
        self.find_friends_btn.raise_()
        self.friend_image.raise_()
        self.msg_list.raise_()
        self.friends_list.raise_()
        self.my_login.raise_()
        self.friend_login.raise_()
        self.my_activity.raise_()
        self.friend_activity.raise_()
        chatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        chatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chatWindow)
        self.statusbar.setObjectName("statusbar")
        chatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(chatWindow)
        QtCore.QMetaObject.connectSlotsByName(chatWindow)

    def retranslateUi(self, chatWindow):
        _translate = QtCore.QCoreApplication.translate
        chatWindow.setWindowTitle(_translate("chatWindow", "chatWindow"))
        self.send_msg_btn.setText(_translate("chatWindow", "Send message"))
        self.find_friends_btn.setText(_translate("chatWindow", "Find friends..."))
        self.my_image.setText(_translate("chatWindow", "Set image"))
        self.my_activity.setText(_translate("chatWindow", "Онлайн"))
        self.friend_activity.setText(_translate("chatWindow", "Офлайн"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chatWindow = QtWidgets.QMainWindow()
    ui = Ui_chatWindow()
    ui.setupUi(chatWindow)
    chatWindow.show()
    sys.exit(app.exec_())
